project:
  render: 
    - _draft.qmd
format:
  pdf:
    documentclass: article
    keep-tex: true
    link-citations: true
    colorlinks: true
    filters: 
      - abstract-section
  html:
    toc: true
    citations-hover: true
    embed-resources: true
    filters: 
      - parse-latex
execute: 
  echo: false
  warning: false
  message: false
bibliography: biblio.bib




